### ISSUE TITLE
Typos in proof of Cauchy's Theorem (Theorem 15.1)

### ISSUE THREAD

**Issue by killianobrien** [twjudson/aata#12]
The second sentence of this proof doesn't read correctly. I think sentence fragments were deleted inadvertently. I suggest it should be split into two sentences and read something like:

"If |G|=p then clearly G itself is the required subgroup. We now assume that every group of order k, where p <= k < n and p divides k, has an element of order p."

**Comment by twjudson** [comment]
Thanks for catching this.  What I had written definitely did not make sense.

Tom Judson

=========
Thomas W. Judson, Associate Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: judsontw@sfasu.edu<mailto:judsontw@sfasu.edu>




On Mar 2, 2017, at 10:06 AM, killianobrien <notifications@github.com<mailto:notifications@github.com>> wrote:


The second sentence of this proof doesn't read correctly. I think sentence fragments were deleted inadvertently. I suggest it should be split into two sentences and read something like:

"If |G|=p then clearly G itself is the required subgroup. We now assume that every group of order k, where p <= k < n and p divides k, has an element of order p."
