### ISSUE TITLE
index tag error - p-groups

### ISSUE THREAD

**Issue by klevasseur** [twjudson/aata#15]
In line 67 of struct.xml, the index tag  seems to be incorrect.  In the html, it appears as 

Groups!p-groups

**Comment by twjudson** [comment]
Nice catch.  I missed this during the conversion to MBX from LaTeX.

Tom

On May 12, 2017, at 1:08 PM, Ken Levasseur <notifications@github.com<mailto:notifications@github.com>> wrote:


In line 67 of struct.xml, the index tag seems to be incorrect. In the html, it appears as

Groups!p-groups
