### ISSUE TITLE
Add an explanation about the \notdivide symbol

### ISSUE THREAD

**Issue by pmarillo** [twjudson/aata#22]
This symbol is first used in chapter 6: Fermat's little theorem.
IMHO this barred symbol could deserve an explanatory note or an additional sentence, as it might be a bit confusing to the reader.
(While I knew about its opposite division symbol '|', as a student in France I've never seen this \notdivide symbol in any maths course from secondary school to CS engineering).

I can create a PR if necessary.

**Comment by twjudson** [comment]
Dear Paul,

Good point.  I added an explanation and the not divide symbol now appears in the notation table.  You should see this in the next snapshot (sometime in January).

Best regards,
Tom

=========
Thomas W. Judson, Associate Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: judsontw@sfasu.edu<mailto:judsontw@sfasu.edu>




On Nov 13, 2017, at 2:02 AM, Paul M. <notifications@github.com<mailto:notifications@github.com>> wrote:


This symbol is first used in chapter 6: Fermat's little theorem.
IMHO this barred symbol could deserve an explanatory note or an additional sentence, as it might be a bit confusing to the reader.
(While I knew about its opposite division symbol '|', as a student in France I've never seen this \notdivide symbol in any maths course from secondary school to CS engineering).

I can create a PR if necessary.
