### ISSUE TITLE
Typo - missing space between words

### ISSUE THREAD

**Issue by acr4** [twjudson/aata#25]
In the “Historical Note” in chapter 3 (Groups), there is a missing space between “polynomials’” and “coefficients”.

**Comment by twjudson** [comment]
Hi Alex,

I made the change.  You will see it in the Snapshot edition, which will be in December or January.

Cheers,
Tom Judson
=========
Thomas W. Judson, Associate Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: judsontw@sfasu.edu<mailto:judsontw@sfasu.edu>

On Aug 25, 2018, at 10:35 AM, Alex Reed <notifications@github.com> wrote:

In the “Historical Note” in chapter 3 (Groups), there is a missing space between “polynomials’” and “coefficients”.
