### ISSUE TITLE
Definition of "function" is confusing

### ISSUE THREAD

**Issue by rjyoung1729** [twjudson/aata#27]
The definition of function in Chapter 1 reads

`We will define a  mapping or function <m>f \subset A \times B</m> from a set <m>A</m> to a set <m>B</m> to be the special type of relation where <m>(a, b) \in f</m> if for every element <m>a \in A</m> there exists a unique element <m>b \in B</m>.`

This seems a little scrambled.  Should this be something like

`the special type of  relation in which for each element <m>a \in A</m> there is a unique element <m>b \in B</m> such that <m>(a, b) \in f</m>.`

as in the 2014 edition?

**Comment by twjudson** [comment]
I reworded the definition.
