### ISSUE TITLE
Partition function is not NP complete

### ISSUE THREAD

**Issue by rjyoung1729** [twjudson/aata#28]
Section 14.2 states that computing the number of partitions of n into positive integers is NP-complete, but I think there may be some confusion with the partition problem (which asks whether positive integers a_1,...,a_n can be partitioned into two sets with equal sums).   Computing p(n) is not NP-complete; Johansson (https://arxiv.org/abs/1205.5991) implemented an algorithm that uses the Hardy-Ramanujan-Rademacher formula to calculate the partition function p(n) in time roughly sqrt(n).  Since the number of digits in p(n) is on the order of sqrt(n), this is softly optimal.

**Comment by twjudson** [comment]
You are certainly correct.  I have rewritten this to say

"There are variations to problem of finding the number of such partitions for any positive integer <m>n</m> that are what computer scientists call <term>NP-complete</term>.
        This effectively means that the problem cannot be solved for a large <m>n</m> because the computations would be too time-consuming for even the largest computer."

I wanted to say something without venturing too far into the details.
