### ISSUE TITLE
2019 Cover image is missing

### ISSUE THREAD

**Issue by smburdick** [twjudson/aata#32]
This link returns a 404: http://abstract.pugetsound.edu/aata/images/cover_aata_2019.png.

**Comment by twjudson** [comment]
Yes, I know.  The problem will be fixed as soon as I receive the image file from Orthogonal Publishing.

**Comment by twjudson** [comment]
We finally have the correct images for the HTML version.  They should appear on the next snapshot, but I believe the latest GitHub version is correct.
