### ISSUE TITLE
Minor omission

### ISSUE THREAD

**Issue by lkubat1101** [twjudson/aata#33]
Likely throughout the book, but specifically in the proof of 1.3.1 and 2 you've invoked the idempotence of or without explicitly stating it.  It might not be a bad idea to include a quick boolean algebra recap so the logic used for the proofs in the book is entirely self-contained.   

As a student, one of the things that helps me make sure I have actually proved something is to label every single step I take in a proof with the name of the theorem or definition that lets me take that step.  

the statement x or x = x may very well seem self-evident, but when you're first learning it's really good to learn not to trust yourself to make tat judgement and rely instead on a previously named definition or proven theorem.  Just giving me a name for the thing that lets me go from {x: x e A or x e A} to {x: x e A} lets me be sure I can actually do it instead of being just pretty sure it sounds right.

Wikipedia's got a pretty good set of basic logic properties, and it wouldn't take too much space to just introduce them without proof as a reference:
Associativity of or:	x or (y or z) = (x or y) or z
Associativity of and:	x and (y and z) = (x and y) and z
Commutativity of or: 	x or y = y or x
Commutativity of and: 	x and y = y and x
Distributivity of and over or:	x and (y or z) = (x and y) or (x and z)
Distributivity of or over and:	x or (y and z) = (x or y) and (x or z)
Identity of or:	x or false = x
Identity of and:	x and true = x
Annihilator for or: 	x or true = true
Annihilator for and: 	x and false = false
Idempotence of or: 	x or x = x
Idempotence of and: 	x and x = x
Absorption: x or (x and y) = 	x = x and (x or y)

Also it'd be some fun foreshadowing for some of the concepts and terms that are to come.  Wait, logic itself is a ring with which iv'e been working with all along!?  No waaaaay!

**Comment by twjudson** [comment]
I decided consciously made the decision not to get too deep into logic in the first chapter; otherwise, the book would be much longer, and it would take too long to get to the actual topics of abstract algebra.  Besides, there are many good sources for this material as you correctly pointed out.
