### ISSUE TITLE
Fix Theorem References

### ISSUE THREAD

**Issue by Jahrme** [twjudson/aata#4]
**Chapter 6, Exercise 13**
In line 155 of source `/aata/src/exercises/cosets.xml` the exercise references `Theorem~6.3`.
This needs to be changed to an `<xref>`, though I am unsure that 6.3 is the correct number as currently 6.3 is a Lemma.

**Chapter 19, Exercise**
In line 346 of source `/aata/src/exercises/boolean.xml` the exercise reference `Theorem~19.14`.
This needs to be changed to an `<xref>`, though I am unsure that 19.14 is the correct number as the exercise is referencing Boolean algebras, however 19.14 is about lattices.

**Comment by rbeezer** [comment]
@twjudson When you fix this, you can place the first 7 or 8 digits of the commit hash in your final comment and it will automatically make a link to the commit itself.  (Once we sync the private repo with the public one.)

**Comment by twjudson** [comment]
Fixed.

Tom

**Comment by Jahrme** [comment]
Thanks!
