### ISSUE TITLE
Exercise unclear on dihedral notation

### ISSUE THREAD

**Issue by kcrisman** [twjudson/aata#48]
Exercise 29 in Chapter 5 asks about `D_8`, `D_{10}`, and `D_n`.  https://github.com/twjudson/aata/blob/master/src/permute.xml#L1559

But is it asking for the center for any `n` (so, even/odd cases, but strange that the examples only ask for even) or for only even `n` (so, notational ambiguity)?  In either case, it should be clarified somewhat.

**Comment by twjudson** [comment]
I agree that this problem needs a bit more guidance, so I put a hint to consider the even and odd case. - Tom

On Sep 26, 2020, at 4:49 PM, kcrisman <notifications@github.com<mailto:notifications@github.com>> wrote:



Exercise 29 in Chapter 5 asks about D_8, D_{10}, and D_n. https://github.com/twjudson/aata/blob/master/src/permute.xml#L1559<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_twjudson_aata_blob_master_src_permute.xml-23L1559&d=DwMCaQ&c=2X_btuPRWkGwRX26NHIotzR6MNUgJAbf6yNNV5-qTbU&r=BQmZUphR5rjzEsIGWo4gOhHhb8A_MVZPtDOMQxdFlh8&m=2b92KUyHTz1AG4smj0MMAS5HCvBO98H34TKuTXiFbR8&s=WV3SMBOw9Qs84l-8O03L6jX0MEL5CnLLRPkGQ9cEFE4&e=>

But is it asking for the center for any n (so, even/odd cases, but strange that the examples only ask for even) or for only even n (so, notational ambiguity)? In either case, it should be clarified somewhat.

**Comment by twjudson** [comment]
Added a hint.

**Comment by twjudson** [comment]
1ZY3612V0305213018

 1ZY3612V0305176649
