### ISSUE TITLE
Left vs right action in Proposition 14.21

### ISSUE THREAD

**Issue by jeremy9959** [twjudson/aata#54]
Consider:
![image](https://user-images.githubusercontent.com/11709993/139863931-cefd95e3-6bea-4c7c-9e2b-6081beeb3643.png)

If G acts on X on the left, and you want a left action of G on Hom(X,Y), then you need an inverse here:
\sigma(f) = f\circ\sigma^{-1}.  Otherwise it's a right action, in which case sigma(f) is confusing.  I think there's no way to avoid
being more explicit here, one way or another.

**Comment by rbeezer** [comment]
Thanks for the reminder on this one.  I've only taught this a few times, and the last time was a while ago.  So I think it'll be best to let Tom decide what needs to be done.

But while I'm here: the fixed set X-tilde is being indexed by \sigma\in G.  Should it instead be indexed by \sigma-tilde\in G-tilde?  Or is it somehow clear that \sigma is an OK index/subscript and it gets promoted to \sigma-tilde?  Am I missing something?

**Comment by jeremy9959** [comment]
Looking at this again, I realize that I had misunderstood what was going on.  I think \tilde{G} is supposed to be the opposite group of G, which is the group made with the same elements as G but in \tilde{G} you have a*b  = ba.
Then this definition does yield a left action by \tilde{G}.  So there's probably no formal obstacle here but it's still confusing,
since \tilde{G} appears out of nowhere.  My original comment was that you can't escape the issues of left and right actions here, and that's still true.  I'm not sure of the best fix.

**Comment by twjudson** [comment]
I see your point.  Certainly, the best way to define a group action is with \sigma^{-1}; however,I don't think that a group action needs to be defined here.  And I would like to avoid making things complicated.  I changed the statement of the Proposition to better fit the situation.  I am closing the issue, but feel free to reopen if you think that there is a need
<img width="802" alt="Screen Shot 2021-11-28 at 7 44 54 AM" src="https://user-images.githubusercontent.com/6010731/143734296-2f9af230-ded9-4d3b-b6ef-a475a5390f30.png">
.
