### ISSUE TITLE
Exercise 17.5.20 cyclotomic polynomials

### ISSUE THREAD

**Issue by spkersten** [twjudson/aata#62]
From other sources I gather that the expression given is only a cyclotomic polynomial when n is prime, while the exercise puts no restrictions on n.

**Comment by twjudson** [comment]
Actually, I think that it can be either.  I have found both definitions.

Tom

On Nov 24, 2022, at 7:31 AM, Sander Kersten ***@***.***> wrote:



From other sources I gather that the expression given is only a cyclotomic polynomial when n is prime, while the exercise puts no restrictions on n.
