### ISSUE TITLE
Feedback on Exercise 21.5.1(d)

### ISSUE THREAD

**Issue by spkersten** [twjudson/aata#63]
Apologies if this is a misunderstanding by me, but exercise 21.5.1(d) seems unreasonably difficult (or perhaps surprisingly so for a first exercise). If I understand correctly (from other books), the minimal polynomial of primitive roots of unity are the cyclotomic polynomials. Figuring that out and proving those are irreducible (when n is not necessarily prime) is hard.

**Comment by twjudson** [comment]
Dear Prof. Kersten,

Given the contents of Chapter 4 (roots of unity), I think that this is a reasonable exercise.

Tom Judson
=========
Thomas W. Judson, Professor
Department of Mathematics and Statistics
Stephen F. Austin State University
P.O. Box 13040-3040 SFA Station
Nacogdoches, TX  75962

OFFICE: 316 Math
TEL: (936) 468-1704
EMAIL: ***@***.***

The views and opinions expressed in this message are my own and do not necessarily reflect the views and opinions of Stephen F. Austin State University, its Board of Regents, or the State of Texas.





On Nov 24, 2022, at 7:32 AM, Sander Kersten ***@***.***> wrote:



Apologies if this is a misunderstanding by me, but exercise 21.5.1(d) seems unreasonably difficult (or perhaps surprisingly so for a first exercise). If I understand correctly (from other books), the minimal polynomial of primitives root of unity are the cyclotomic polynomials. Figuring that out and proving those are irreducible (when n is not necessarily prime) is hard.
